<script setup lang="ts">
import type { YearlyReportData } from '@/types/yearly'
import YearlyReviewSlide from '../YearlyReviewSlide.vue'

defineProps<{
  data: YearlyReportData
}>()

const badges = [
  { name: '赛博盟友', icon: 'i-heroicons-user-group', color: 'text-yellow-400' },
  { name: '深夜战友', icon: 'i-heroicons-moon', color: 'text-purple-400' },
  { name: '表情包巨头', icon: 'i-heroicons-face-smile', color: 'text-pink-400' },
]
</script>

<template>
  <YearlyReviewSlide>
    <template #background>
      <div class="absolute inset-0 bg-[url('https://ui.nuxt.com/grid.svg')] opacity-5"></div>
    </template>

    <div
      class="w-full bg-white/60 backdrop-blur-md rounded-3xl p-8 border border-white/50 shadow-2xl space-y-8 transform hover:scale-[1.02] transition-transform duration-500"
    >
      <!-- Header -->
      <div class="text-center space-y-2">
        <div class="text-sm text-slate-500 tracking-widest uppercase">ChatLab 年度报告</div>
        <h2 class="text-3xl font-bold text-slate-900">2025 我们的双向奔赴</h2>
      </div>

      <!-- Badges -->
      <div class="flex justify-center gap-4">
        <div v-for="badge in badges" :key="badge.name" class="flex flex-col items-center gap-2">
          <div
            class="w-12 h-12 rounded-full bg-white flex items-center justify-center border border-pink-100 shadow-sm"
          >
            <UIcon :name="badge.icon" class="w-6 h-6" :class="badge.color.replace('text-', 'text-')" />
          </div>
          <div class="text-xs text-slate-600">{{ badge.name }}</div>
        </div>
      </div>

      <!-- Key Stats Grid -->
      <div class="grid grid-cols-2 gap-4">
        <div class="bg-white/50 rounded-xl p-4 text-center border border-white/50">
          <div class="text-2xl font-bold text-slate-800">{{ (data.overview.totalMessages / 10000).toFixed(1) }}w</div>
          <div class="text-xs text-slate-500">总消息</div>
        </div>
        <div class="bg-white/50 rounded-xl p-4 text-center border border-white/50">
          <div class="text-2xl font-bold text-slate-800">{{ data.nightOwl.lateNightCount }}</div>
          <div class="text-xs text-slate-500">深夜陪伴</div>
        </div>
        <div class="bg-white/50 rounded-xl p-4 text-center border border-white/50">
          <div class="text-2xl font-bold text-slate-800">{{ data.emotions.laughterCount }}</div>
          <div class="text-xs text-slate-500">快乐时刻</div>
        </div>
        <div class="bg-white/50 rounded-xl p-4 text-center border border-white/50">
          <div class="text-2xl font-bold text-slate-800">{{ data.overview.totalDurationMinutes }}</div>
          <div class="text-xs text-slate-500">陪伴分钟</div>
        </div>
      </div>

      <!-- Footer -->
      <div class="pt-4 border-t border-slate-200 text-center">
        <button
          class="w-full py-3 bg-pink-500 text-white rounded-xl font-bold hover:bg-pink-600 transition-colors flex items-center justify-center gap-2 shadow-lg shadow-pink-500/20"
        >
          <UIcon name="i-heroicons-arrow-down-tray" class="w-5 h-5" />
          保存为图片
        </button>
        <div class="mt-4 text-xs text-slate-400">Generated by ChatLab</div>
      </div>
    </div>
  </YearlyReviewSlide>
</template>
